version: '3'
services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/kafka:latest
    networks:
    - parrot
    external_links:
    - zookeeper
    ports:
    - 9092:9092
    - 8081:8081
    - 8082:8082
    - 8084:8083
    - 8001:8000
    environment:
    - KAFKA_REST_PROXY_URL=http://localhost:8082
    - PROXY=true
    - PROXY_SKIP_VERIFY=true
    - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
